### ISSUE TITLE
Unable to import modules into rollup.config.js

### ISSUE THREAD

**Issue by mattpilott** [neuekit/utilities#29]
With the current neuekit utils setup in M2 it's not possible to import a module into a rollup config. Whilst the issue is non-sensical as the import statement *is* using import, i feel this may have something to do with the juggling act of uvu and esm

```bash
(node:9313) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/Matt/Sites/Neue Kit Utilities/src/index.js
require() of ES modules is not supported.
require() of /Users/Matt/Sites/Neue Kit Utilities/src/index.js from /Users/Matt/Sites/Sapper Start/rollup.config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/Matt/Sites/Neue Kit Utilities/package.json.

    at Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Object.require.extensions..js (/Users/Matt/Sites/Sapper Start/node_modules/.pnpm/sapper@0.29.0_svelte@3.32.1/node_modules/sapper/dist/create_manifest_data.js:4307:21)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/Matt/Sites/Sapper Start/rollup.config.js:19:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.require.extensions..js (/Users/Matt/Sites/Sapper Start/node_modules/.pnpm/sapper@0.29.0_svelte@3.32.1/node_modules/sapper/dist/create_manifest_data.js:4304:28)
    at Module.load (internal/modules/cjs/loader.js:928:32)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9313) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9313) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mattpilott** [comment]
This is now resolved
